# Generated by Django 3.0.3 on 2020-12-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
